FROM oraclelinux:8

RUN dnf install -y \
        python39 \
        sudo \
        curl \
        gnupg2 \
        ca-certificates && \
    alternatives --set python3 /usr/bin/python3.9 && \
    dnf clean all

# Добавьте пользователя для Ansible
RUN useradd -m ansible && \
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ansible

USER ansible
WORKDIR /home/ansible

CMD ["sleep", "infinity"]
